global:
  hosts:
    https: false
    domain: 192.168.4.112.nip.io
  ingress:
    configureCertmanager: false
    tls:
      enabled: false
  shell:
    port: 32022

installCertmanager: false

nginx-ingress:
  controller:
    replicaCount: 1
    minAavailable: 1
    service:
      type: NodePort
      nodePorts:
        gitlab-shell: 32022
        http: 32080

gitlab-runner:
  runners:
    privileged: true

prometheus:
  install: false

registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1

gitlab:
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
  gitlab-exporter:
    enabled: false
  webservice:
    minReplicas: 1
    maxReplicas: 1
