#kind: Cluster
#apiVersion: kind.x-k8s.io/v1alpha4
##name: local-ci
#nodes:
#  - role: control-plane
#    extraPortMappings:
#    - containerPort: 30003  # Harbor UI
#      hostPort: 30003
#      listenAddress: "0.0.0.0"
#    - containerPort: 32080  # GitLab UI
#      hostPort: 80
#      listenAddress: "0.0.0.0"
#    - containerPort: 32022  # GitLab SSH
#      hostPort: 32022
#      listenAddress: "0.0.0.0"

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # containerPort below must match the values file:
      #   nginx-ingress.controller.service.nodePorts.http
      # Change hostPort if port 80 is already in use.
      - containerPort: 32080
        hostPort: 80
        listenAddress: "0.0.0.0"
        # containerPort below must match the values file:
        #   nginx-ingress.controller.service.nodePorts.ssh
        # Using high-numbered hostPort assuming port 22 is
        #   already in use.
      - containerPort: 32022
        hostPort: 32022
        listenAddress: "0.0.0.0"